### ISSUE TITLE
Fix SSL errors with Nexus CLI when deploying from Nexus

### ISSUE THREAD

**Issue by reset** [RiotGamesCookbooks/artifact-cookbook#33]

**Comment by KAllan357** [comment]
Not too sure about this one.

The code on https://github.com/RiotGames/artifact-cookbook/blob/master/providers/deploy.rb#L314 

`remote = NexusCli::RemoteFactory.create(config, false)`

The 2nd parameter ensure we don't verify. Perhaps this issue means that we should be able to configure this option, because usually SSL should be working appropriately and defaulting to ignore checking is bad.
