### ISSUE TITLE
Circular dependency with nexus cookbook

### ISSUE THREAD

**Issue by tknerr** [RiotGamesCookbooks/artifact-cookbook#37]
artifact depends on nexus, and nexus depends on artifact.

Not that it's only "bad style", but it also causes other tools to break, e.g.:
http://permalink.gmane.org/gmane.comp.sysutils.chef.user/7557

**Comment by reset** [comment]
@tknerr we'll look into fixing the circular dependency in these two cookbooks - it wasn't something we planned. On a side note the resolver in Berkshelf should handle the circular dependency just fine in the mean time - was this not the behavior you observed?

**Comment by KAllan357** [comment]
Actually this was something I did intentionally. Perhaps the circular dependency should be broken - especially the artifact cookbook's dependence on nexus - since artifact is only using the `nexus::cli` recipe.

It seems to me like some circular dependencies in cookbooks should actually be an "okay" thing. The nexus cookbook's dependency on artifact is a bit weak - Nexus is an artifact server that has a deployable; bringing in the artifact cookbook gives one access to the `artifact_deploy` resource so we can easily deploy the artifact server.

**Comment by reset** [comment]
@KAllan357 nexus should depend on artifact since we use it to deploy the nexus server, but I think we can work it out so the artifact cookbook doesn't require the nexus one.

**Comment by capoferro** [comment]
I think a good solution is to separate the Nexus cookbook into Nexus Server and Nexus cookbooks, as Nexus Server is the only bit that requires Artifact, and Artifact will never require Nexus Server.
